GET https://node-studies-3ko5.onrender.com/videos

###

POST https://node-studies-3ko5.onrender.com/videos
Content-Type: application/json

{
    "title": "title",
    "description": "description",
    "duration": 150
}

###
DELETE https://node-studies-3ko5.onrender.com/videos/34af2d9d-71fc-4a24-aa6f-ae7870c56813

###

PUT https://node-studies-3ko5.onrender.com/videos/12752141-0142-45d6-b5fa-0d1ead322d44
Content-Type: application/json

{
    "title": "Yuri",
    "description": "Yuri's Draw my Life",
    "duration": 500
}